### ISSUE TITLE
arm64 compilation issue (Win11)

### ISSUE THREAD

**Issue by ArminiusTux** [N1ckn1ght/ACE#29]
Dear @N1ckn1ght ,

I've encoutered the following compilation issue under Windows on ARM64:

```
$ cargo build --release
  Downloaded proc-macro2 v1.0.71
  Downloaded syn v2.0.43
  Downloaded 2 crates (292.8 KB) in 1.08s
   Compiling proc-macro2 v1.0.71
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling siphasher v0.3.11
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.17
   Compiling byteorder v1.5.0
   Compiling getrandom v0.2.11
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.2
   Compiling rand_chacha v0.3.1
   Compiling phf_generator v0.11.2
   Compiling quote v1.0.33
   Compiling syn v2.0.43
   Compiling phf_macros v0.11.2
   Compiling phf v0.11.2
   Compiling ace v1.1.2 (C:\CODING\ACE)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\main.rs:1:12
  |
1 | #![feature(test)]
  |            ^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `ace` (bin "ace") due to 1 previous error

```

**Comment by N1ckn1ght** [comment]
feature test is a Rust **_nightly_** feature. I am afraid it won't work on Rust **_stable_**.

**Comment by ArminiusTux** [comment]
Thank you for the reply, I was actually cloning your latest release version.

`git clone -b 'v1.1.2' https://github.com/N1ckn1ght/ACE`

**Comment by N1ckn1ght** [comment]
> Thank you for the reply, I was actually cloning your latest release version.
> 
> `git clone -b 'v1.1.2' https://github.com/N1ckn1ght/ACE`

I meant that the rust #![feature(test)] itself always requires Nigthly version of Rust: https://doc.rust-lang.org/unstable-book/library-features/test.html 
I used it for 'cargo bench' feature. I think **I should've used nightly toolchain** in cargo, but so far there was only one actual benchmark test, so in the end, I just removed it with nightly feature for now.

**Master branch should be launching in stable now**,
_Versions prior would require setting up rust nightly as default rust toolchain in terminal._

Thank you for the issue, I researched the question, and if future updates would require usage of nightly features, the toolchain will be changed as well (afaik this should work https://stackoverflow.com/questions/66681150/how-to-tell-cargo-to-use-nightly)
